"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const repoRoot = path.resolve(__dirname, "..", "..");
const presetPath = path.join(repoRoot, "wordpress-plugin", "presets", "real-estate.json");
const renderAdapterPath = path.join(repoRoot, "wordpress-plugin", "includes", "adapters", "render-adapter.php");
const singleAdapterPath = path.join(repoRoot, "wordpress-plugin", "includes", "adapters", "single-adapter.php");
const restApiPath = path.join(repoRoot, "wordpress-plugin", "includes", "api", "rest.php");

function readText(filePath) {
  return fs.readFileSync(filePath, "utf8");
}

test("real estate preset carries the canonical Kyiv brokerage story", () => {
  const preset = JSON.parse(readText(presetPath));
  const heroSection = preset.pages.home.sections.find((section) => section.type === "hero");

  assert.equal(preset.site.name, "Kyiv Turquoise Realty");
  assert.equal(heroSection.title, "Find Your Place in Kyiv");
  assert.equal(heroSection.subtitle, "Explore apartments, houses, and commercial spaces across Kyiv.");
  assert.equal(heroSection.cta_label, "Browse properties");
  assert.equal(preset.pages.contact.title, "Contact Kyiv Turquoise Realty");
  assert.equal(preset.pages.contact.text, "Schedule a viewing or request more details about properties in Kyiv.");
});

test("public real estate renderers do not expose beta or proof wording", () => {
  const renderAdapter = readText(renderAdapterPath);
  const singleAdapter = readText(singleAdapterPath);

  for (const source of [renderAdapter, singleAdapter]) {
    assert.ok(!source.includes("Generated real estate catalog with validated property pages."));
    assert.ok(!source.includes("Validation proof available in Site Factory"));
    assert.ok(!source.includes("Crocoblock-powered generated site"));
    assert.ok(!source.includes("Generated by Site Factory"));
  }

  assert.ok(!renderAdapter.includes("Real Estate Beta"));
  assert.ok(!renderAdapter.includes("Generated real estate service"));
  assert.ok(!renderAdapter.includes("Explore generated Kyiv listings with stable filters, sorting, pagination, and Request Viewing links."));
});

test("real estate public fallbacks stay aligned to the Kyiv story", () => {
  const restApi = readText(restApiPath);

  assert.match(restApi, /'hero_title'\s*=>\s*\(string\)\s*\(\s*\$hero_section\['title'\]\s*\?\?\s*'Find Your Place in Kyiv'\s*\)/);
  assert.match(restApi, /'hero_subtitle'\s*=>\s*\(string\)\s*\(\s*\$hero_section\['subtitle'\]\s*\?\?\s*'Explore apartments, houses, and commercial spaces across Kyiv\.'\s*\)/);
  assert.match(restApi, /'contact_intro'\s*=>\s*\(string\)\s*\(\s*\$contact\['text'\]\s*\?\?\s*'Schedule a viewing or request more details about properties in Kyiv\.'\s*\)/);
  assert.ok(restApi.includes("function factory_rest_get_real_estate_public_brand( array $blueprint ): string"));
  assert.ok(restApi.includes("function factory_rest_get_real_estate_footer_description( array $blueprint ): string"));
});
